### ISSUE TITLE
Storing progress status 

### ISSUE THREAD

**Issue by m-d-s** [psu-capstone/dlab-api#16]
Having some way to identify how far along in the issue ranking process a user is. In case they log out or the system crashes

**Comment by midnightlynx** [comment]
Since we're intending every value/objective/policy to have some sort of rating assigned from that user when they've completed that step, then we can just check if there's unrated values, unrated objectives or unrated policies to tell if they still need to complete a step.

I imagine we also need an endpoint to do this?

**Comment by m-d-s** [comment]
As of right now, the ranking process does not get saved if a user does not submit. A user can also only submit once they have all items ranked. We could make it so that a post gets made every time a user drops an item in a target button. It might just be alright to not have un-submitted rankings not persist, just to avoid the hassle.

**Comment by midnightlynx** [comment]
I think I prefer not making the post to save until they submit, both to simplify this, and for performance reasons.
